name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  catalina_build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  big_sur_build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  ubuntu16.04_build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  ubuntu18.04_build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  ubuntu20.04_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
